services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy_db
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pharmacy_db"]
      interval: 5s
      timeout: 5s
      retries: 10
  server:
    build: .
    environment:
      PORT: 5000
      CLIENT_ORIGIN: http://localhost:4200
      DATABASE_URL: postgres://postgres:postgres@db:5432/pharmacy_db
      JWT_SECRET: mynameissivakumar
      JWT_EXPIRES_IN: 1d
    ports: ["5000:5000"]
    depends_on:
      db:
        condition: service_healthy
volumes: { pgdata: {} }
